### ISSUE TITLE
STOP EFFASHA

### ISSUE THREAD

**Issue by urbaxadeeznuts** [Famana-Universalis-Team/FamanaUniversalis#68]
THEY NEED TO BE STOPPPED

**Comment by Adartho** [comment]
Who must be stopped?
![external-content duckduckgo com](https://user-images.githubusercontent.com/64917020/148102815-4a5ece5a-a122-43b0-b2b7-bdc3922f6bb8.jpg)

**Comment by u1145** [comment]
external-content duckduckgo com

**Comment by Cilria** [comment]
Effashan Hyper War of 500
